### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by dronenb** [Togo/hotkeyEVE#1]
Hi @Togo,

First of all, thank you for creating such a unique and useful application. Every few years I lose my copy of Hotkey EVE and have to go find a place to find an archived copy of it. I realize that the software should probably be considered as abandonware at this point, but I appreciate the fact that you took the time to post the source code on GitHub (I just found the repo for the first time). What is the licensing on this project? Would you be willing to add a permissive LICENSE to the project so there could be the possibility this project can be forked and carried on?

**Comment by Togo** [comment]
Hi @dronenb ,

Wow. I didn't think the app was still being used. I've added a license. But I can't give any guarantee that the app is still functional.
